---
title: "TCoG Analysis"
format: html
knitr:
  opts_chunk: 
    message: false
fig-format: svg
params: 
  exptag: "exp3curved"
  nucpath: "06c_ResynthesizedRecordingsExp3CURVED/ConstantScaling_"
  sf: 70
---

```{r setup}
library(tidyverse)
library(targets)
library(sosprosody)
library(rPraat)
source("Helpers/tcog_helpers.R")
source('Helpers/bezier_helpers.R')
sf <- params$sf
exp_tag <- params$exptag

dep <-  tar_read(assemble_resyntheses)
syl_specs <- tar_read(syllable_specification)
three_syl_words <- tar_read(three_syl_words)
```

```{r}
pt_df <- readRDS("CalculatedFiles/bottomoutMono_prepped_pt_70.RDS")

tcogs <- 
  pt_df |> 
  group_by(file, utterance, tune, pa_val, bt_val) |> 
  dplyr::filter(is_nuclear,
                tune == 'HLL') |> 
  mutate(timepoint_norm = timepoint - min(timepoint),
         timepoint_norm = timepoint_norm / max(timepoint_norm)) |> 
  dplyr::select(timepoint, timepoint_norm, semitone_difference, hz) |>
  summarize(tcog_t = get_tcog(abs(hz-90), timepoint_norm),
            tcog_f = get_tcog(timepoint_norm, hz-90))

bottomout_tcog_2 <- tcog_from_prepped_regions("CalculatedFiles/bottomoutMono_prepped_pt_70.RDS")
```


```{r}
bottomout_tcog <- tcog_from_prepped_regions2('06d_ResynthesizedRecordingsBottomoutMonotonal/ConstantScaling_70/PitchTiers/pitchtier_df.rds')
bottomout_tcog_plot <- plot_recording_tcog(dplyr::filter(bottomout_tcog, !utterance %in% three_syl_words), three_syl_words)

gradual_tcog_100 <- tcog_from_prepped_regions2('06_ResynthesizedRecordings/ConstantScaling_100/PitchTiers/pitchtier_df.rds')
gradual_100_plot <- plot_recording_tcog(dplyr::filter(gradual_tcog_100, !utterance %in% three_syl_words), three_syl_words)
# 
gradual_tcog_70 <- tcog_from_prepped_regions2('06_ResynthesizedRecordings/ConstantScaling_70/PitchTiers/pitchtier_df.rds')
gradual_70_plot <- plot_recording_tcog(dplyr::filter(gradual_tcog_70, !utterance %in% three_syl_words), three_syl_words)
# 
# library(patchwork)
# (bottomout_tcog_plot+
#     ylim(c(60, 125)) +
#     ggtitle('Bottomout - 100%')) + 
#   (gradual_100_plot+
#      ylim(c(60, 125)) +
#      ggtitle('Gradual - 100%')) + 
#   (gradual_70_plot+
#      ylim(c(60, 125)) +
#      ggtitle('Gradual - 70%'))

bottomout_tcog <- tcog_from_prepped_regions('CalculatedFiles/bottomoutMono_prepped_pt_70.RDS')
bottomout_tcog_plot <- plot_recording_tcog(dplyr::filter(bottomout_tcog2, !utterance %in% three_syl_words), three_syl_words)
bottomout_tcog2 <- tcog_from_prepped_regions('CalculatedFiles/bottomoutMono_prepped_pt_100.RDS')
bottomout_tcog_plot2 <- plot_recording_tcog(dplyr::filter(bottomout_tcog2, !utterance %in% three_syl_words), three_syl_words)

gradual_tcog_1002 <- tcog_from_prepped_regions('CalculatedFiles/exp1_prepped_pt_100.RDS')
gradual_100_plot2 <- plot_recording_tcog(dplyr::filter(gradual_tcog_1002, !utterance %in% three_syl_words), three_syl_words)

gradual_tcog_702 <- tcog_from_prepped_regions('CalculatedFiles/exp1_prepped_pt_70.RDS')
gradual_70_plot2 <- plot_recording_tcog(dplyr::filter(gradual_tcog_702, !utterance %in% three_syl_words), three_syl_words)
library(patchwork)

((bottomout_tcog_plot+
    # ylim(c(60, 130)) +
    # xlim(c(44, 57))+
    ggtitle('Bottomout - 70%'))+
(bottomout_tcog_plot2+
    # ylim(c(60, 130)) +
    # xlim(c(44, 57))+
    ggtitle('Bottomout - 100%'))) /
  ((gradual_100_plot2+
     # ylim(c(60, 130)) +
     # xlim(c(44, 57))+
     ggtitle('Gradual - 100%')) + 
  (gradual_70_plot2+
     # ylim(c(60, 130)) +
     # xlim(c(44, 57))+
     ggtitle('Gradual - 70%')))

```

